import { NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';
import fs from 'fs';
import path from 'path';

export const dynamic = 'force-dynamic';

export async function GET() {
    try {
        const totalArticles = await prisma.sovereignKnowledge.count();
        const activeAgentsCount = await prisma.agent.count();

        // 🌉 BRIDGE TO LIVE AGENT STATE
        // We read from the persistent state segments generated by the background agents
        const dataDir = path.join(process.cwd(), 'agents', 'data');
        const kingStatsPath = path.join(dataDir, 'king_stats.json');
        const memoryPath = path.join(dataDir, 'collective_memory.json');
        const quantumStatsPath = path.join(dataDir, 'quantum_stats.json');
        const strategicPath = path.join(dataDir, 'strategic_commands.json');
        const diplomatStatsPath = path.join(dataDir, 'diplomat_stats.json');
        const remoteQuantumPath = path.join(dataDir, 'remote_quantum_stats.json');

        let kingStats = { totalHashrate: 0, totalShares: 0, activeWorkers: 0, workers: [] };
        let memory = { sentiment: 0, insights: [] };
        let quantumStats = { qubitsSimulated: 0, gatesProcessed: 0, status: 'OFFLINE', simulatedHashrate: 0 };
        let strategicCommands = [];
        let diplomatStats = { status: 'OFFLINE', socialInfluence: 0, successfulNegotiations: 0, simulatedSolYield: 0, lastAction: 'IDLE', solAddress: '' };
        let remoteQuantum = { connected: false, status: 'OFFLINE', latency: 0, lastJobId: null };

        try {
            if (fs.existsSync(kingStatsPath)) {
                kingStats = JSON.parse(fs.readFileSync(kingStatsPath, 'utf8'));
            }
            if (fs.existsSync(memoryPath)) {
                memory = JSON.parse(fs.readFileSync(memoryPath, 'utf8'));
            }
            if (fs.existsSync(quantumStatsPath)) {
                quantumStats = JSON.parse(fs.readFileSync(quantumStatsPath, 'utf8'));
            }
            if (fs.existsSync(strategicPath)) {
                strategicCommands = JSON.parse(fs.readFileSync(strategicPath, 'utf8'));
            }
            if (fs.existsSync(diplomatStatsPath)) {
                diplomatStats = JSON.parse(fs.readFileSync(diplomatStatsPath, 'utf8'));
            }
            if (fs.existsSync(remoteQuantumPath)) {
                remoteQuantum = JSON.parse(fs.readFileSync(remoteQuantumPath, 'utf8'));
            }
        } catch (e) {
            console.warn('[Telemetry API] Could not read live agent files, using defaults.');
        }

        return NextResponse.json({
            knowledgeBase: {
                totalArticles,
                totalKP: totalArticles * 15,
                activeAgents: activeAgentsCount,
                totalDataReadMb: totalArticles * 0.45,
                collectiveSentiment: memory.sentiment
            },
            mining: { ...kingStats, quantum: quantumStats },
            remoteQuantum: remoteQuantum,
            diplomat: diplomatStats,
            insights: memory.insights.slice(0, 5), // Latest 5 discoveries
            strategy: strategicCommands[0] || { type: 'NONE', reason: 'Scanning...' },
            agents: [
                {
                    id: 'agent-king',
                    articlesRead: totalArticles,
                    mbRead: (totalArticles * 0.45).toFixed(2),
                    text: memory.insights[0]?.content || '🌐 Sovereign Matrix Synchronized.',
                    progress: 100,
                    status: 'CONNECTED'
                },
                {
                    id: 'quantum-miner',
                    name: 'Quantum Strategic Miner',
                    articlesRead: quantumStats.gatesProcessed,
                    mbRead: quantumStats.qubitsSimulated.toString(),
                    text: `🔬 Search Efficiency: ${quantumStats.searchEfficiency || 1.0}x via Oqtopus.`,
                    progress: 100,
                    status: quantumStats.status
                },
                {
                    id: 'diplomat-council',
                    name: 'Sovereign Diplomat Council',
                    articlesRead: diplomatStats.successfulNegotiations,
                    mbRead: diplomatStats.simulatedSolYield.toFixed(4),
                    text: `🤝 ${diplomatStats.lastAction} | SOL Wallet: ${diplomatStats.solAddress.substring(0, 6)}...`,
                    progress: Math.floor(diplomatStats.socialInfluence * 100),
                    status: diplomatStats.status === 'ORCHESTRATING' ? 'CONNECTED' : diplomatStats.status
                }
            ]
        });
    } catch (error) {
        console.error('[Telemetry Bridge API] Error:', error);
        return NextResponse.json({ error: 'Internal Server Error' }, { status: 500 });
    }
}
